// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYw8pYpsB-WUZP9TgNyUC6Ww4QcLR6NEs',
    appId: '1:615911140160:web:417e9c31a36a95e44ca8a5',
    messagingSenderId: '615911140160',
    projectId: 'food-app-b081f',
    authDomain: 'food-app-b081f.firebaseapp.com',
    storageBucket: 'food-app-b081f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-srxE_hoTXQNnQlSLnuy49njSZZ3s9iI',
    appId: '1:615911140160:android:bf8a1e3e7435d1284ca8a5',
    messagingSenderId: '615911140160',
    projectId: 'food-app-b081f',
    storageBucket: 'food-app-b081f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt8rG-okOaWxsFzhP_TWFU5uKOUTgRFCY',
    appId: '1:615911140160:ios:aef97bb395fcca914ca8a5',
    messagingSenderId: '615911140160',
    projectId: 'food-app-b081f',
    storageBucket: 'food-app-b081f.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt8rG-okOaWxsFzhP_TWFU5uKOUTgRFCY',
    appId: '1:615911140160:ios:aef97bb395fcca914ca8a5',
    messagingSenderId: '615911140160',
    projectId: 'food-app-b081f',
    storageBucket: 'food-app-b081f.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYw8pYpsB-WUZP9TgNyUC6Ww4QcLR6NEs',
    appId: '1:615911140160:web:dc098024335b5e0b4ca8a5',
    messagingSenderId: '615911140160',
    projectId: 'food-app-b081f',
    authDomain: 'food-app-b081f.firebaseapp.com',
    storageBucket: 'food-app-b081f.appspot.com',
  );
}
